"""Add dependent tables for Attendances and Grades

Revision ID: 47489c15a6c9
Revises: ead99d6b9f69
Create Date: 2023-11-24 13:24:25.391648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47489c15a6c9'
down_revision = 'ead99d6b9f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('grade_types')
    op.drop_table('subjects')
    op.drop_table('attendance_types')
    op.drop_table('attendances')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
